services:
  postgres:
    build:
      context: ..
      dockerfile: docker/DockerfileDb
    command:
      [
        'postgres',
        '-c',
        'log_statement=all',
        '-c',
        'logging_collector=on',
        '-c',
        'log_directory=/var/log/postgresql',
        '-c',
        'log_filename=postgresql.log',
      ]
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: docker/DockerfileApp
    depends_on:
      - postgres
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  postgres_logs:

networks:
  app-network:
    driver: bridge
